name: gopls
on:
  push:
    paths:
      - .github/workflows/gopls.yml
      - "dockerfiles/gopls/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/gopls.yml
      - "dockerfiles/gopls/**"
      - .github/workflows/reusable.yml

jobs:
  gopls:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: gopls
      version: v0.9.3
