name: impl
on:
  push:
    paths:
      - .github/workflows/impl.yml
      - "dockerfiles/impl/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/impl.yml
      - "dockerfiles/impl/**"
      - .github/workflows/reusable.yml

jobs:
  impl:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: impl
      version: v1.1.0
