name: kubectx
on:
  push:
    paths:
      - .github/workflows/kubectx.yml
      - "dockerfiles/kubectx/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/kubectx.yml
      - "dockerfiles/kubectx/**"
      - .github/workflows/reusable.yml

jobs:
  kubectx:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: kubectx
      version: v0.9.4
