name: kubens
on:
  push:
    paths:
      - .github/workflows/kubens.yml
      - "dockerfiles/kubens/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/kubens.yml
      - "dockerfiles/kubens/**"
      - .github/workflows/reusable.yml

jobs:
  kubens:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: kubens
      version: v0.9.4
