name: mockgen
on:
  push:
    paths:
      - .github/workflows/mockgen.yml
      - "dockerfiles/mockgen/**"
      - .github/workflows/reusable.yml
  pull_request:
    paths:
      - .github/workflows/mockgen.yml
      - "dockerfiles/mockgen/**"
      - .github/workflows/reusable.yml

jobs:
  mockgen:
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      name: mockgen
      version: v0.6.0
